server:
  port: 8081

spring:
  config:
    import: "configserver:http://localhost:8888"

  application:
    name: appointment-service

  cloud:
    config:
      fail-fast: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/doctors-db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh
